"""COSMIC mutational signature descriptions."""

SIGNATURE_DESCRIPTIONS = {
    "SBS1": "Deamination of 5-methylcytosine",
    "SBS2": "APOBEC Cytidine Deaminase",
    "SBS3": "Defective homologous recombination",
    "SBS4": "Tobacco smoking",
    "SBS5": "Unknown (Clock-like)",
    "SBS6": "Defective DNA mismatch repair",
    "SBS7a": "Ultraviolet light exposure",
    "SBS7b": "Ultraviolet light exposure",
    "SBS7c": "Ultraviolet light exposure",
    "SBS7d": "Ultraviolet light exposure",
    "SBS8": "Unknown",
    "SBS9": "Polymerase eta somatic hypermutation",
    "SBS10a": "POLE mutation",
    "SBS10b": "POLE mutation",
    "SBS10c": "Defective POLD1",
    "SBS10d": "Defective POLD1",
    "SBS11": "Alkylating agents",
    "SBS12": "Unknown",
    "SBS13": "APOBEC Cytidine Deaminase",
    "SBS14": "Concurrent POLE mutation and defective MMR",
    "SBS15": "Defective DNA mismatch repair",
    "SBS16": "Unknown",
    "SBS17a": "Unknown",
    "SBS17b": "Unknown",
    "SBS18": "Damage by reactive oxygen species",
    "SBS19": "Unknown",
    "SBS20": "Defective mismatch repair and POLD1 mutations",
    "SBS21": "Defective DNA mismatch repair",
    "SBS22": "Aristolochic acid exposure",
    "SBS23": "Unknown",
    "SBS24": "Aflatoxin exposure",
    "SBS25": "Unknown",
    "SBS26": "Defective DNA mismatch repair",
    "SBS27": "Unknown",
    "SBS28": "Unknown",
    "SBS29": "Tobacco chewing",
    "SBS30": "Defective base excision repair (NTHL1)",
    "SBS31": "Platinum treatment",
    "SBS32": "Azathioprine treatment",
    "SBS33": "Unknown",
    "SBS34": "Unknown",
    "SBS35": "Platinum treatment",
    "SBS36": "Defective base excision repair (MUTYH)",
    "SBS37": "Unknown",
    "SBS38": "Indirect effects of UV light",
    "SBS39": "Unknown",
    "SBS40": "Unknown",
    "SBS41": "Unknown",
    "SBS42": "Haloalkane exposure",
    "SBS43": "Unknown",
    "SBS44": "Defective DNA mismatch repair",
    "SBS45": "Artifact",
    "SBS46": "Artifact",
    "SBS47": "Artifact",
    "SBS48": "Artifact",
    "SBS49": "Artifact",
    "SBS50": "Artifact",
    "SBS51": "Artifact",
    "SBS52": "Artifact",
    "SBS53": "Artifact",
    "SBS54": "Artifact",
    "SBS55": "Artifact",
    "SBS56": "Artifact",
    "SBS57": "Artifact",
    "SBS58": "Artifact",
    "SBS59": "Artifact",
    "SBS60": "Artifact",
    "SBS84": "Activation-induced cytidine deaminase",
    "SBS85": "Activation-induced cytidine deaminase",
    "SBS86": "Unknown chemotherapy treatment",
    "SBS87": "Thiopurine treatment",
    "SBS88": "Colibactin exposure",
    "SBS89": "Unknown",
    "SBS90": "Duocarmycin exposure",
    "SBS91": "Unknown",
    "SBS92": "Tobacco smoking",
    "SBS93": "Unknown",
    "SBS94": "Unknown",
    "SBS95": "Artifact",
    "SBS96": "Artifact",
    "SBS97": "Artifact",
    "SBS98": "Artifact",
    "SBS99": "Artifact",
    "ID1": "Slippage during DNA replication",
    "ID2": "Slippage during DNA replication",
    "ID3": "Tobacco smoking",
    "ID4": "Unknown",
    "ID5": "Unknown",
    "ID6": "Defective homologous recombination",
    "ID7": "Defective DNA mismatch repair",
    "ID8": "Defective DNA double-strand break repair",
    "DBS1": "Ultraviolet light exposure",
    "DBS2": "Tobacco smoking",
    "DBS3": "Polymerase epsilon exonuclease domain mutations",
    "DBS4": "Unknown",
    "DBS5": "Platinum treatment",
    "DBS6": "Unknown",
    "DBS7": "Defective DNA mismatch repair",
    "DBS8": "Unknown",
    "DBS9": "Unknown",
    "DBS10": "Defective DNA mismatch repair",
    "DBS11": "APOBEC Cytidine Deaminase",
}
